service: rust-talk

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  versionFunctions: false
  region: eu-central-1

plugins:
  - cargo-lambda-serverless
  - serverless-webpack

custom:
  webpack:
    packager: npm
    webpackConfig: 'webpack.config.js'

package:
  individually: true

functions:
  rust_lambda:
    handler: bootstrap
    cargo:
      path: 'target/lambda/rust_talk_rust/bootstrap'
    url:
      cors: true

  node_lambda:
    handler: src/rust_talk_node.main
    runtime: 'nodejs18.x'
    url:
      cors: true

